# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flights.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'flights.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rflights.proto\x12\x12googleflightsearch\"\x1b\n\x0b\x41irportInfo\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\"\x89\x01\n\rFlightSegment\x12\x16\n\x0eorigin_airport\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x65parture_date\x18\x02 \x01(\t\x12\x1b\n\x13\x64\x65stination_airport\x18\x03 \x01(\t\x12\x14\n\x0c\x61irline_code\x18\x05 \x01(\t\x12\x15\n\rflight_number\x18\x06 \x01(\t\"\x88\x02\n\x07TripLeg\x12\x13\n\x0btravel_date\x18\x02 \x01(\t\x12\x33\n\x08segments\x18\x04 \x03(\x0b\x32!.googleflightsearch.FlightSegment\x12/\n\x06origin\x18\r \x01(\x0b\x32\x1f.googleflightsearch.AirportInfo\x12\x34\n\x0b\x64\x65stination\x18\x0e \x01(\x0b\x32\x1f.googleflightsearch.AirportInfo\x12\x1c\n\x0fmax_connections\x18\x05 \x01(\x05H\x00\x88\x01\x01\x12\x1a\n\x12preferred_airlines\x18\x06 \x03(\tB\x12\n\x10_max_connections\"\xe7\x01\n\x13\x46lightSearchRequest\x12.\n\titinerary\x18\x03 \x03(\x0b\x32\x1b.googleflightsearch.TripLeg\x12\x33\n\x0b\x63\x61\x62in_class\x18\t \x01(\x0e\x32\x1e.googleflightsearch.CabinClass\x12:\n\x0fpassenger_types\x18\x08 \x03(\x0e\x32!.googleflightsearch.PassengerType\x12/\n\ttrip_type\x18\x13 \x01(\x0e\x32\x1c.googleflightsearch.TripType*\x94\x01\n\nCabinClass\x12\x1b\n\x17\x43\x41\x42IN_CLASS_UNSPECIFIED\x10\x00\x12\x17\n\x13\x43\x41\x42IN_CLASS_ECONOMY\x10\x01\x12\x1f\n\x1b\x43\x41\x42IN_CLASS_PREMIUM_ECONOMY\x10\x02\x12\x18\n\x14\x43\x41\x42IN_CLASS_BUSINESS\x10\x03\x12\x15\n\x11\x43\x41\x42IN_CLASS_FIRST\x10\x04*k\n\x08TripType\x12\x19\n\x15TRIP_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fTRIP_TYPE_ROUND\x10\x01\x12\x15\n\x11TRIP_TYPE_ONE_WAY\x10\x02\x12\x18\n\x14TRIP_TYPE_MULTI_CITY\x10\x03*\xa2\x01\n\rPassengerType\x12\x1e\n\x1aPASSENGER_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14PASSENGER_TYPE_ADULT\x10\x01\x12\x18\n\x14PASSENGER_TYPE_CHILD\x10\x02\x12\x1e\n\x1aPASSENGER_TYPE_INFANT_SEAT\x10\x03\x12\x1d\n\x19PASSENGER_TYPE_INFANT_LAP\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flights_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CABINCLASS']._serialized_start=708
  _globals['_CABINCLASS']._serialized_end=856
  _globals['_TRIPTYPE']._serialized_start=858
  _globals['_TRIPTYPE']._serialized_end=965
  _globals['_PASSENGERTYPE']._serialized_start=968
  _globals['_PASSENGERTYPE']._serialized_end=1130
  _globals['_AIRPORTINFO']._serialized_start=37
  _globals['_AIRPORTINFO']._serialized_end=64
  _globals['_FLIGHTSEGMENT']._serialized_start=67
  _globals['_FLIGHTSEGMENT']._serialized_end=204
  _globals['_TRIPLEG']._serialized_start=207
  _globals['_TRIPLEG']._serialized_end=471
  _globals['_FLIGHTSEARCHREQUEST']._serialized_start=474
  _globals['_FLIGHTSEARCHREQUEST']._serialized_end=705
# @@protoc_insertion_point(module_scope)
